---
abstract: 'Mount any Plack application to a URL root'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst: 5.90001
  Catalyst::Test: 0
  FindBin: 0
  HTTP::Request::Common: 0
  Moose: 0
  Plack::App::File: 0
  Plack::App::URLMap: 0
  Plack::Component: 0
  Plack::Util: 0
  Scalar::Util: 0
  Test::Most: 0.25
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-URLMap
requires:
  Moose::Role: 0
  namespace::autoclean: 0
version: 0.001
